begin;

create table if not exists public.demarcador_versiones (
	version_id uuid primary key default gen_random_uuid(),
	numero bigint generated by default as identity unique,
	estado text not null default 'borrador'
		check (estado in ('borrador', 'publicada', 'archivada')),
	esquema integer not null default 1 check (esquema > 0),
	artefacto jsonb not null check (jsonb_typeof(artefacto) = 'object'),
	huella_fuente text not null,
	fuente_actualizada_en timestamptz null,
	total_familias integer not null check (total_familias >= 0),
	total_familias_variantes integer not null check (total_familias_variantes >= 0),
	total_variantes_demarcables integer not null check (total_variantes_demarcables >= 0),
	generado_por uuid null references public.editores (user_id) on update cascade on delete set null,
	generado_en timestamptz not null default now(),
	publicado_por uuid null references public.editores (user_id) on update cascade on delete set null,
	publicado_en timestamptz null,
	updated_at timestamptz not null default now()
);

comment on table public.demarcador_versiones is
	'Instantáneas inmutables del demarcador generadas desde vocabularios y políticas editoriales.';

create unique index if not exists demarcador_versiones_unica_publicada_idx
	on public.demarcador_versiones ((estado))
	where estado = 'publicada';

create index if not exists demarcador_versiones_generado_en_idx
	on public.demarcador_versiones (generado_en desc);

create index if not exists demarcador_versiones_huella_fuente_idx
	on public.demarcador_versiones (huella_fuente);

drop trigger if exists trigger_demarcador_versiones_updated_at
	on public.demarcador_versiones;
create trigger trigger_demarcador_versiones_updated_at
before update on public.demarcador_versiones
for each row execute function public.actualizar_updated_at();

alter table public.demarcador_versiones enable row level security;

drop policy if exists "demarcador_versiones_select_publicada"
	on public.demarcador_versiones;
create policy "demarcador_versiones_select_publicada"
on public.demarcador_versiones
for select
to anon, authenticated
using (estado = 'publicada');

drop policy if exists "demarcador_versiones_select_admin_ip"
	on public.demarcador_versiones;
create policy "demarcador_versiones_select_admin_ip"
on public.demarcador_versiones
for select
to authenticated
using (public.auth_is_admin_or_ip());

drop policy if exists "demarcador_versiones_insert_admin_ip"
	on public.demarcador_versiones;
create policy "demarcador_versiones_insert_admin_ip"
on public.demarcador_versiones
for insert
to authenticated
with check (public.auth_is_admin_or_ip());

grant select on table public.demarcador_versiones to anon;
grant select, insert on table public.demarcador_versiones to authenticated;

create or replace function public.publicar_demarcador_version(p_version_id uuid)
returns public.demarcador_versiones
language plpgsql
security definer
set search_path = public
as $$
declare
	v_version public.demarcador_versiones;
begin
	if not public.auth_is_admin_or_ip() then
		raise exception 'Solo admin o IP pueden publicar una versión del demarcador'
			using errcode = '42501';
	end if;

	select *
	into v_version
	from public.demarcador_versiones
	where version_id = p_version_id
	for update;

	if v_version.version_id is null then
		raise exception 'Versión del demarcador no encontrada'
			using errcode = 'P0002';
	end if;

	update public.demarcador_versiones
	set
		estado = 'archivada',
		updated_at = now()
	where estado = 'publicada'
		and version_id <> p_version_id;

	update public.demarcador_versiones
	set
		estado = 'publicada',
		publicado_por = auth.uid(),
		publicado_en = now(),
		updated_at = now()
	where version_id = p_version_id
	returning * into v_version;

	return v_version;
end;
$$;

revoke all on function public.publicar_demarcador_version(uuid) from public;
grant execute on function public.publicar_demarcador_version(uuid) to authenticated;

commit;
